# Generated by Django 4.1 on 2022-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_mini_img', models.ImageField(upload_to='img')),
                ('card_mini_name', models.CharField(max_length=100)),
                ('card_mini_category', models.CharField(max_length=100)),
                ('card_mini_status', models.CharField(max_length=10)),
                ('card_mini_amount', models.IntegerField(default=1)),
                ('card_mini_price', models.IntegerField(default=0)),
                ('card_mini_basket', models.BooleanField(default=True)),
            ],
        ),
    ]
