# Generated by Django 4.1 on 2022-08-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_options_alter_shop_card_mini_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_basket',
            new_name='basket',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='card_mini_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='card_mini_category',
        ),
    ]
