# Generated by Django 4.1 on 2022-08-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_amount',
            field=models.IntegerField(default=1, verbose_name='Выбранное количество'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_basket',
            field=models.BooleanField(default=True, verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_img',
            field=models.ImageField(upload_to='img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='card_mini_status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
    ]
