# Generated by Django 4.1 on 2022-08-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_category_shop_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='basket',
        ),
        migrations.AddField(
            model_name='shop',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория'),
        ),
    ]
